UI/Controllers/BookController.cs
using Business.Concrete;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using UI.Models;


namespace UI.Controllers
{
    public class BookController : Controller
    {
        private BookManager _bookManager;
        private Book_GenreManager _bookGenreManager;
        private GenreManager _genreManager;
        public BookController()
        {
            _bookManager = new BookManager();
            _bookGenreManager = new Book_GenreManager();
            _genreManager = new GenreManager();
        }

        public IActionResult Index(int genre)
        {
            var model = new BookViewModel
            {
                Books = genre > 0 ? _bookManager.GetBooksByGenre(_bookGenreManager.GetByGenreID(genre)) : _bookManager.GetAll()
            };
            return View(model);
        }

        public IActionResult BookDetails(string ISBN)
        {
            var model = new BookViewModel
            {
                Book = _bookManager.GetById(ISBN),
                GenreNames = _genreManager.GetGenresByID(_bookGenreManager.GetBookGenresByISBN(ISBN))
            };
            return View(model);
        }

        public IActionResult AddBook()
        {
            var model = new BookViewModel
            {
                Genres = _genreManager.GetAll()
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult AddBook(Book book, List<int> genres, IFormFile image)
        {
            if (image != null)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);
                FileInfo fileInfo = new FileInfo(image.FileName);
                string fileName = image.FileName;
                string fileNameWithPath = Path.Combine(path, fileName);
                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    image.CopyTo(stream);
                }
            }
            Book bookToAdd = new Book
            {
                ISBN = book.ISBN,
                Title = book.Title,
                Summary = book.Summary,
                LanguageID = book.LanguageID,
                ImageSource = image.FileName,
                Author = book.Author
            };
            _bookManager.Add(bookToAdd);
            foreach (var genreID in genres)
            {
                Book_Genre book_genre = new Book_Genre
                {
                    BookISBN = book.ISBN,
                    GenreID = genreID
                };
                _bookGenreManager.Add(book_genre);
            }

            return RedirectToAction("Index");
        }
        public IActionResult EditBook(string ISBN)
        {
            var model = new BookViewModel
            {
                Book = _bookManager.GetById(ISBN),
                Genres = _genreManager.GetAll()
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult EditBook(Book book, List<int> genres, IFormFile image)
        {
            if (image != null)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);
                FileInfo fileInfo = new FileInfo(image.FileName);
                string fileName = image.FileName;
                string fileNameWithPath = Path.Combine(path, fileName);
                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    image.CopyTo(stream);
                }
            }


            List<Book_Genre> book_Genres = _bookGenreManager.GetAllByISBN(book.ISBN).ToList();
            foreach (var item in book_Genres)
            {
                _bookGenreManager.Delete(item);
            }

            Book bookToAdd = new Book
            {
                ISBN = book.ISBN,
                Title = book.Title,
                Summary = book.Summary,
                LanguageID = book.LanguageID,
                Author = book.Author
            };
            if (image != null)
            {
                bookToAdd.ImageSource = image.FileName;
            }
            else
            {
                bookToAdd.ImageSource = _bookManager.GetById(book.ISBN).ImageSource;
            }

            _bookManager.Update(bookToAdd);

            foreach (var genreID in genres)
            {
                Book_Genre book_genre = new Book_Genre
                {
                    BookISBN = book.ISBN,
                    GenreID = genreID
                };
                _bookGenreManager.Add(book_genre);
            }

            return RedirectToAction("Index");

        }
        public IActionResult DeleteBook(string ISBN)
        {

            _bookManager.Delete(_bookManager.GetById(ISBN));
            return RedirectToAction("Index");
        }
    }
}

UI/ViewComponents/GenreListViewComponent.cs
using Business.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using UI.Models;

namespace UI.ViewComponents
{
    public class GenreListViewComponent : ViewComponent
    {
        private GenreManager _genreManager;
        public GenreListViewComponent()
        {
            _genreManager = new GenreManager();
        }
        public ViewViewComponentResult Invoke()
        {
            var model = new GenreViewModel
            {
                Genres = _genreManager.GetAll(),
                CurrentGenre = Convert.ToInt32(HttpContext.Request.Query["genre"])
            };
            return View(model);

        }
    }
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow" style="background-color: orange">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>MEF Reads</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index"><b>Books</b></a>
                        </li>
                        @if (UserInfo.user != null)
                        {
                            @if (UserInfo.user.Role == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index"><b>Manage Users</b></a>
                                </li>

                            }
                        }
                        @if (UserInfo.user == null)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><b>Login</b></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout"><b>@UserInfo.user.Username | Logout</b></a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="bg">
        <div class="container mt-3 p-0" >
            <img src="../images/reads.jpg" alt="reads" style="height: 100%; width: 100%; object-fit:contain">
            
            <main role="main" class="pb-3">
                @RenderBody()
            </main>

        </div>
    
    

        
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>

UI/Views/Shared/_LayoutAddBooks.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/book.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow" style="background-color:orange">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>MEF Reads</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index"><b>Books</b></a>
                        </li>
                        @if (UserInfo.user != null)
                        {
                            @if (UserInfo.user.Role == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index"><b>Manage Users</b></a>
                                </li>

                            }
                        }
                        @if (UserInfo.user == null)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><b>Login</b></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout"><b>@UserInfo.user.Username | Logout</b></a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="bg">
          <div class="container mt-3" style="left:111px;">
        <main role="main" class="pb-3">
            <div class="row" >
                <div class="col-9">@RenderBody()</div>
            </div>         
        </main>
    </div>
    </div>
  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI/Views/Shared/_LayoutBookDetails.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow" style="background-color: orange">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>MEF Reads</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index"><b>Books</b></a>
                        </li>
                        
                        @if (UserInfo.user != null)
                        {
                            @if (UserInfo.user.Role == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index"><b>Manage Users</b></a>
                                </li>

                            }
                        }
                        @if (UserInfo.user == null)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><b>Login</b></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout"><b>@UserInfo.user.Username | Logout</b></a>
                            </li>
                        }

                          
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="bg">
        <div class="container mt-3 p-0" style="top:100px;">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>

        </div>
    
    

        
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>

UI/Views/Shared/_LayoutBooks.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
</head>
<style>
    .bg{
        position:relative!important;
        padding-top:10px;
    }
</style>
<body style="margin-bottom:0;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow" style="background-color:orange">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>MEF Reads</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index"><b>Books</b></a>
                        </li>
                        @if (UserInfo.user != null)
                        {
                            @if (UserInfo.user.Role == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index"><b>Manage Users</b></a>
                                </li>

                            }
                        }
                        @if (UserInfo.user == null)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><b>Login</b></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout"><b>@UserInfo.user.Username | Logout</b></a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="bg">
          <div class="container mt-3" style="left:-140px;">
        <main role="main" class="pb-3">
            <div class="row" >
                <div class="col-3">@await Component.InvokeAsync("GenreList")</div>
                <div class="col-9">@RenderBody()</div>
            </div>
            
        </main>
    </div>
    </div>
  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI/Views/Shared/_LayoutEdit.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow" style="background-color:orange">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>MEF Reads</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index"><b>Books</b></a>
                        </li>
                        @if (UserInfo.user != null)
                        {
                            @if (UserInfo.user.Role == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index"><b>Manage Users</b></a>
                                </li>

                            }
                        }
                        @if (UserInfo.user == null)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><b>Login</b></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout"><b>@UserInfo.user.Username | Logout</b></a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="bg">
          <div class="container mt-3" style="left:111px;">
        <main role="main" class="pb-3">
            <div class="row" >
                <div class="col-9">@RenderBody()</div>
            </div>         
        </main>
    </div>
    </div>
  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI/Views/Shared/_LayoutUsers.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
</head>
<body style="margin-bottom:0;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light" style="background-color:orange;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>MEF Reads</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index"><b>Books</b></a>
                        </li>
                        @if (UserInfo.user != null)
                        {
                            @if (UserInfo.user.Role == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index"><b>Manage Users</b></a>
                                </li>

                            }
                        }
                        @if (UserInfo.user == null)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><b>Login</b></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout"><b>@UserInfo.user.Username | Logout</b></a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="userbg">
        <div class="container" style="left:111px;">
            <main role="main" class="pb-3">
                <div class="row">

                    <div class="col-9">@RenderBody()</div>
                </div>

            </main>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>